language: python
python:
  - 3.4
  - 3.5
  - 3.6
  - nightly

# environment variables
env:
 - TESTING=True

install:
  - sudo apt-get install libvirt-dev
  - pip install codecov
  - pip install nose-cov
  - pip install pycodestyle
  - pip install pydocstyle
  - pip install dodgy
  - pip install isort
  - pip install mypy
  - pip install -r requirements.txt
  - pip install Flask-Testing
  - pip install blinker
script:
  - nosetests --nocapture --with-cov --cov-config .coveragerc
  - dodgy
  - mypy mod_*
  - pydocstyle --config=./.pydocstylerc
  - isort -rc --check-only
after_success:
  - codecov
